includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms.yml"

benchmarks:
  dacapochopin:
    - fop

modifiers:
  heap4g:
    type: JVMArg
    val: -Xms4G -Xmx4G
  no_heapsize:
    type: NoImplicitHeapsizeModifier

configs:
  - "temurin-21|dacapochopin_jdk21"
  - "temurin-21|dacapochopin_jdk21|epsilon|no_heapsize|heap4g"