includes:
  - "./base/runbms.yml"

overrides:
  "suites.dacapo2006.timing_iteration": 5
  "suites.dacapobach.timing_iteration": 5
  "suites.dacapo2006.callback": "probe.Dacapo2006Callback"
  "suites.dacapobach.callback": "probe.DacapoBachCallback"

modifiers:
  probes_cp:
    type: JVMClasspath
    val: "/home/zixianc/MMTk-Dev/evaluation/probes /home/zixianc/MMTk-Dev/evaluation/probes/probes.jar"
  probes_native:
    type: JVMArg
    val: "-Djava.library.path=/home/zixianc/MMTk-Dev/evaluation/probes"
  probes_rustmmtk:
    type: JVMArg
    val: "-Dprobes=RustMMTk"
  value_opts_example:
    type: EnvVar
    var: "FOOBAR{0}"
    val: "BUZZ{1}"
  benchmark_cp:    # This is required because the main class is the one in the probes rather than the one in SPECjvm98
    type: JVMClasspath
    val: "/usr/share/benchmarks/SPECjvm98"

runtimes:
  jdk-mmtk:
    type: OpenJDK
    release: 11
    home: "/home/zixianc/MMTk-Dev/evaluation/build/jdk-mmtk/jdk"

benchmarks:
  specjvm98:
    - _213_javac

configs:
  - "jdk-mmtk|ms|s|c2|ss|tph|probes_cp|probes_rustmmtk|probes_native|benchmark_cp|value_opts_example-42-43" # benchmark_cp has to come after probes_cp so that the correct main class can be found
# Also do not forget to set --workdir when running the runbms since SPECjvm98 has to be executed in its own directory