runtimes:
  adoptopenjdk-8:
    type: OpenJDK
    release: 8
    home: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
  adoptopenjdk-11:
    type: OpenJDK
    release: 11
    home: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
  adoptopenjdk-12:
    type: OpenJDK
    release: 12
    home: /usr/lib/jvm/adoptopenjdk-12-hotspot-amd64
  adoptopenjdk-13:
    type: OpenJDK
    release: 13
    home: /usr/lib/jvm/adoptopenjdk-13-hotspot-amd64
  adoptopenjdk-14:
    type: OpenJDK
    release: 14
    home: /usr/lib/jvm/adoptopenjdk-14-hotspot-amd64
  adoptopenjdk-15:
    type: OpenJDK
    release: 15
    home: /usr/lib/jvm/adoptopenjdk-15-hotspot-amd64
  adoptopenjdk-16:
    type: OpenJDK
    release: 16
    home: /usr/lib/jvm/adoptopenjdk-16-hotspot-amd64
