suites:
  dacapo2006:
    type: DaCapo
    release: "2006"
    path: /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        antlr: 5
        chart: 21
        eclipse: 25
        hsqldb: 135
    timing_iteration: 3
    timeout: 120
  dacapobach:
    type: DaCapo
    release: "9.12"
    path: /usr/share/benchmarks/dacapo/dacapo-9.12-bach.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        avrora: 5
        fop: 37
        jython: 31
        luindex: 7
        pmd: 41
        sunflow: 17
        xalan: 8
    timing_iteration: 3
    timeout: 120
  dacapobach-mr1:
    type: DaCapo
    release: "9.12"
    path: /usr/share/benchmarks/dacapo/dacapo-9.12-MR1-bach.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        avrora: 5
        fop: 39
        jython: 32
        luindex: 9
        pmd: 41
        sunflow: 17
        xalan: 10
    timing_iteration: 3
    timeout: 120
  dacapobach-mr1-java6:
    type: DaCapo
    release: "9.12"
    path: /usr/share/benchmarks/dacapo/dacapo-9.12-MR1-bach-java6.jar
    timing_iteration: 3
    timeout: 120
    minheap_values: {}
  dacapochopin-29a657f:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-29a657f.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        avrora: 7
        batik: 253
        biojava: 191
        cassandra: 89
        eclipse: 437
        fop: 19
        graphchi: 255
        h2: 1154
        h2o: 73
        jme: 55
        jython: 37
        # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
        # kafka: inf
        luindex: 42
        lusearch: 23
        pmd: 243
        sunflow: 33
        tradebeans: 169
        tradesoap: 133
        tomcat: 25
        xalan: 9
        zxing: 96
      temurin-17-G1:
        avrora: 7
        batik: 189
        biojava: 95
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        jme: 29
        jython: 25
        luindex: 42
        lusearch: 21
        pmd: 156
        sunflow: 29
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 8
        zxing: 97
        lusearch_huge: 122 # {name: lusearch_large, bm_name: lusearch, size: large}
        lusearch_large: 142 # {name: lusearch_huge, bm_name: lusearch, size: huge, timing_iteration: 2}
      temurin-11-G1:
        avrora: 5
        batik: 185
        biojava: 95
        cassandra: 1026
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 62
        jme: 29
        jython: 27
        luindex: 40
        lusearch: 25
        pmd: 158
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 101
        xalan: 7
        zxing: 96
    timing_iteration: 3
    timeout: 120
  dacapochopin-f480064:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-f480064.jar
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1:
        avrora: 5
        batik: 186
        biojava: 96
        cassandra: 87
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 83
        jme: 29
        jython: 27
        kafka: 201
        luindex: 41
        lusearch: 26
        pmd: 43
        # spring: .inf
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 113
        xalan: 7
        zxing: 98
      temurin-17-G1:
        avrora: 7
        batik: 190
        biojava: 95
        # cassandra: .inf
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        # h2o: .inf
        jme: 29
        jython: 25
        kafka: 197
        luindex: 42
        lusearch: 25
        pmd: 45
        # spring: .inf
        sunflow: 27
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 7
        zxing: 101
    timing_iteration: 3
    timeout: 120
  dacapochopin-6e411f33:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-6e411f33.jar
    minheap: mmtk-openjdk-11-MarkCompact
    minheap_values:
      mmtk-openjdk-11-MarkCompact:
        avrora: 8
        batik: 426
        biojava: 197
        cassandra: 117
        eclipse: 439
        fop: 24
        graphchi: 187
        h2: 1122
        h2o: 893
        jme: 236
        jython: 48
        kafka: 233
        luindex: 25
        lusearch: 36
        pmd: 291
        spring: 110
        sunflow: 37
        tradebeans: .inf
        tradesoap: .inf
        tomcat: 55
        xalan: 22
        zxing: 427
      mmtk-openjdk-11-G1:
        avrora: 7
        batik: 1068
        biojava: 189
        cassandra: 119
        eclipse: 427
        fop: 73
        graphchi: 258
        h2: 908
        h2o: 175
        jme: 235
        jython: 309
        kafka: 219
        luindex: 39
        lusearch: 29
        pmd: 262
        spring: 78
        sunflow: 33
        tomcat: 47
        tradebeans: .inf
        tradesoap: .inf
        xalan: 19
        zxing: 95
    timing_iteration: 3
    timeout: 120
