includes:
  - "./jvms.yml"
  - "./suites.yml"
  - "./modifiers.yml"

# Can override with command line argument -i
invocations: 10
# Can override with command line argument -m
minheap_multiplier: 1.0
heap_range: 6
spread_factor: 1
remote_host: "squirrel.moma"
