runtimes:
  temurin-8:
    type: OpenJDK
    release: 8
    home: /usr/lib/jvm/temurin-8-jdk-amd64
  temurin-11:
    type: OpenJDK
    release: 11
    home: /usr/lib/jvm/temurin-11-jdk-amd64
  temurin-17:
    type: OpenJDK
    release: 17
    home: /usr/lib/jvm/temurin-17-jdk-amd64
